image: node:alpine

cache:
  paths:
    - node_modules/

build:
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  script:
    - yarn install --frozen-lockfile 

test:
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  needs:
    - build
  dependencies:
    - "build"
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
     - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
  script:
    - yarn test-ci


